#!/bin/zsh

mkdir binutils-build
mkdir binutils-install
cd binutils-build
../binutils-${V_BINUTILS}/configure \
    --host=i686-w64-mingw32 \
    --prefix=/c/Users/Public/frc${V_YEAR}/roborio \
    --target=arm-frc${V_YEAR}-linux-gnueabi \
    "--with-pkgversion=GNU Binutils for FRC ${V_YEAR}" \
    --enable-poison-system-directories \
    --with-sysroot=/c/Users/Public/frc${V_YEAR}/roborio/arm-frc${V_YEAR}-linux-gnueabi \
    --enable-plugins \
    --disable-nls \
    --enable-lto \
    --with-build-sysroot=/usr/local/arm-frc${V_YEAR}-linux-gnueabi
make -j3
DESTDIR=$PWD/../binutils-install make install
cd ../binutils-install
