#!/bin/zsh

mkdir gdb-build
mkdir gdb-install
cd gdb-build
../gdb-${V_GDB}/configure \
    --host=i686-w64-mingw32 \
    --prefix=/c/Users/Public/frc${V_YEAR}/roborio \
    --target=arm-frc${V_YEAR}-linux-gnueabi \
    --with-sysroot=/c/Users/Public/frc${V_YEAR}/roborio/arm-frc${V_YEAR}-linux-gnueabi \
    --enable-plugins \
    --disable-nls \
    --with-pkgversion="GDB for FRC ${V_YEAR}" \
    --disable-nls \
    --with-expat \
    --with-libexpat-prefix=$PWD/../expat-install/usr/local/
# --with-python=$PWD/../makes/python-config-gdb
make -j4
DESTDIR=$PWD/../gdb-install make install
cd ../gdb-install
i686-w64-mingw32-strip --remove-section=.comment --remove-section=.note --strip-unneeded **/*.exe
