#!/bin/zsh

rm -rf tree-install
mkdir tree-install
rsync gcc-install/ tree-install -a --copy-links
rsync binutils-install/ tree-install -a --copy-links
rsync sysroot-install/ tree-install -a --copy-links
rsync gdb-install/ tree-install -a --copy-links
cd tree-install/c/Users/Public/frc${V_YEAR}/roborio
du -hs .
i686-w64-mingw32-strip bin/*.exe
i686-w64-mingw32-strip arm-frc*/bin/*.exe
find libexec -name \*.exe | xargs i686-w64-mingw32-strip
rm -rf share/info share/man

pushd arm-frc${V_YEAR}-linux-gnueabi/usr/include
patch -p4 < ../../../../../../../../../makes/case-sensitive-includes.diff
popd
rm -rf lib/xtables

du -hs .
