#!/bin/zsh

rm -rf tree-install
mkdir tree-install
rsync gcc-install/ tree-install -a --copy-links
rsync binutils-install/ tree-install -a --copy-links
rsync sysroot-install/ tree-install -a --copy-links
rsync gdb-install/ tree-install -a --copy-links
cd tree-install/
du -hs .

strip usr/local/bin/*
strip usr/local/arm-frc*/bin/*
find usr/local/libexec -type f |xargs strip

du -hs .
