#!/bin/zsh

mkdir binutils-build
mkdir binutils-install
cd binutils-build
../binutils-${V_BINUTILS}/configure --prefix=/usr/local --target=arm-frc-linux-gnueabi '--with-pkgversion=GNU Binutils for FRC' --enable-poison-system-directories --with-sysroot=/usr/local/arm-frc-linux-gnueabi --disable-nls --enable-lto --with-build-sysroot=/usr/local/arm-frc-linux-gnueabi --disable-werror
make -j3
DESTDIR=$PWD/../binutils-install make install
cd ../binutils-install
#strip --remove-section=.comment --remove-section=.note --strip-unneeded **/*.exe
