#!/bin/zsh

mkdir gdb-build
mkdir gdb-install
cd gdb-build
../gdb-${V_GDB}/configure --target=arm-linux-gnueabi --prefix=/usr --with-pkgversion='GDB for FRC' --disable-nls --with-libexpat --with-python=no --with-system-gdbinit=/usr/share/arm-linux-gnueabi-gdbinit --with-gdb-datadir=/usr/share/gdb-arm-linux-gnueabi --with-sysroot=/usr/arm-frc-linux-gnueabi/
make
DESTDIR=$PWD/../gdb-install make install
cd ../gdb-install

